# Generated by Django 4.2.1 on 2023-05-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Daily_posts', '0002_postcomment_newpost_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='comment',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Daily_posts.newpost'),
        ),
    ]
