# Generated by Django 4.2.1 on 2023-06-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Daily_posts', '0004_newpost_author_newpost_created_at_postcomment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Daily_posts.newpost'),
        ),
    ]
