# Generated by Django 4.2.1 on 2023-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daily_posts', '0006_alter_postcomment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newpost',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
